export const USER_REGISTRATION_START = "USER_REGISTRATION_START"
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS"
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL"

export const USER_LOGIN_START = "USER_LOGIN_START"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const CREATE_USER_START = "CREATE_USER_START"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"

export const DELETE_USER_START = "DELETE_USER_START"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const UPDATE_USER_START = "UPDATE_USER_START"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const GET_ALL_USERS_START = "GET_ALL_USERS_START"
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"

export const REMOVE_ALERT = 'REMOVE_ALERT'

export const USER_LOGOUT = 'USER_LOGOUT'
